# -*- coding: utf-8 -*-
"""processing_strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cr8J0tgmWu-ispZYI7ZmbOCUifFCdFkE

Processing Strings From early iPod Reviews
"""

# mytext: A list of strings whose elements are the lines of “ipod.txt”

with open("ipod.txt", 'r') as inFile:
  mytext = inFile.readlines()

print(mytext)

# length_ipod: A number equal to the number of lines of “ipod.txt”

with open("ipod.txt") as inFile:
    lines = inFile.readlines()
    length_ipod = len(lines)

print(length_ipod)

# nchar_ipod: A list of numbers whose elements are the number of 
# characters in different lines of “ipod.txt”

with open("ipod.txt", 'r') as inFile:
  lines = inFile.readlines()
  nchar_ipod = [len(s) for s in lines]

print(nchar_ipod)

# index_longlines: A list of numbers whose elements are the indices 
# of the lines of “ipod.txt” which have more than 100 characters

index_longlines = [i for i, s in enumerate(lines) if len(s) > 100]

print(index_longlines)

# longlines_ipod.txt: A txt file that contains only the lines of 
# “ipod.txt” that have more than 100 characters. (Use write(), a for loop, and an if 
# statement to create this file.)

longlines_ipod = [line for line in enumerate(lines) if len(line) > 100]

with open("longlines_ipod.txt", 'w') as outFile:
  for line in longlines_ipod:
    outFile.write(line)

"""Creating Column Data Frames"""

# df11: A one-column data frame that contains the addresses of the real 
# estate properties whose prices are exclusively between 200K and 300K

import pandas as pd

df = pd.read_csv("Sacramentorealestatetransactions.csv", encoding = "latin1")

# look at column names
cols = df.columns
print(cols)

# the one-column data frame
df11 = df[(df['price'] >= 200000) | (df['price'] <= 300000)]['street'].copy()
print(df11)

# df12: A two-column data frame that contains the latitudes and 
# longitudes of the real estate properties whose types are either “Condo” or “Multi-Family”

df12 = df[(df['type'] == 'Condo') | (df['type'] == 'Multi-Family')][['latitude', 'longitude']]
print(df12)